services:
    napcat:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - TZ=Asia/Shanghai
            - NAPCAT_UID=${NAPCAT_UID}
            - NAPCAT_GID=${NAPCAT_GID}
        image: mlikiowa/napcat-docker:latest
        labels:
            createdBy: Apps
        mac_address: ${MAC_ADDRESS}
        privileged: true
        restart: always
        ports:
            - ${PANEL_APP_PORT_HTTP}:6099/tcp
            - "3000-3001:3000-3001/tcp"
        volumes:
            - /opt/1panel/apps/napcat/data:/app/.config/QQ
            - /opt/1panel/apps/napcat/config:/app/napcat/config
            - /opt/1panel/apps/napcat/logs:/app/napcat/logs
            - /opt/1panel/apps/astrbot/astrbot/data:/AstrBot/data
